### ISSUE TITLE
how can i create database and how can I get login user name and password

### ISSUE THREAD

**Issue by Manivasakan** [Karpenko-Vadym/RAMS#10]
Hi ,
I download the source code.
it created identity tables only when I run it.
there is no any other tables
what is the user name and password.

**Comment by Karpenko-Vadym** [comment]
Hi there,

I added readme (RAMS Readme.doc) to my github repository with instructions
on how to set up the project.

I hope it helps.

Thank you!

Vadym Karpenko

**Comment by Karpenko-Vadym** [comment]
Please keep in mind that there is one outstanding issue related to JSON
serialization. When there is too much data, API requests become slower and
slower. The easiest way to fix it is to update API Controllers and
requesting Controllers to send and receive ViewModels (instead of Models)
without the properties that point to the parent. This will remove
self-referencing loop and fix the serialization issue.

I meant to address this matter, but didnt have time to do it.

Thank you!

**Comment by Manivasakan** [comment]
thanks a lot
